<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cadabra"
 *
 * Auto generated by Extension Builder 2015-12-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Cadabra',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Marcel Wieser',
    'author_email' => 'typo3dev@marcel-wieser.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '',
    'constraints' => array(
        'depends' => array(
            'typo3' => '7.6.0-7.6.99',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);